name: inshort_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  logger: ^2.6.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  retrofit: ^4.5.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  vector_math: ^2.1.4
  share_plus: ^7.0.2
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
